### ISSUE TITLE
Failed to compile shader: pixel

### ISSUE THREAD

**Issue by AdamGoodApp** [NVlabs/instant-ngp#228] opened 2022-02-22 09:27 UTC
When meshing the model with Mesh it! I get the following error in console.

```
18:16:31 ERROR    Failed to compile shader: pixel
18:16:31 ERROR    0:1(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

18:16:31 ERROR    Failed to compile shader: shader program
18:16:31 ERROR    error: no shaders attached to the program
```

The result of the obj file is a bunch of blobs.

Running testbed command in WSL2, X11 server on Windows 10.

**Comment by Tom94** [comment] 2022-02-22 09:33
Hi there, this is a duplicate of https://github.com/NVlabs/instant-ngp/issues/111

**Closed by Tom94** 2022-02-22 09:33 UTC
