### ISSUE TITLE
CUDA compiler identification source file   "CMakeCUDACompilerId.cu" missing

### ISSUE THREAD

**Issue by teachyourselfcoding** [NVlabs/instant-ngp#126] opened 2022-02-09 13:45 UTC
> CMake Error at /home/trajic/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:726 (message):
>   Compiling the CUDA compiler identification source file
>   "CMakeCUDACompilerId.cu" failed.
> 
>   Compiler: /usr/local/cuda-11.4/bin/nvcc
> 
>   Build flags:
> 
>   Id flags: -v
> 
>   
> 
>   The output was:
> 
>   No such file or directory
> 
>   
> 
>   
> 
> Call Stack (most recent call first):
>   /home/trajic/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
>   /home/trajic/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
>   /home/trajic/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
>   CMakeLists.txt:11 (PROJECT)

Ran into this error when running "cmake . -B build" after updating cuda version. Can't for the life of me figure out why. Thank you in advance for your time.

**Comment by teachyourselfcoding** [comment] 2022-02-09 14:08
Bypassed this issue when I re-pulled into a new repo and ran it on my base environment. Seems to be a conflict with my anaconda environment. I will leave this issue open, hope someone can help to pinpoint the problem.

**Comment by Tom94** [comment] 2022-02-13 08:56
In the interest of keeping the issues board minimal/organized, I'm gonna close this one in any case. Supporting non-native CUDA environments is relatively low on our priority list right now. Thanks for the heads-up, though!

**Closed by Tom94** 2022-02-13 08:56 UTC

**Comment by SawyDust1228** [comment] 2022-08-25 09:55
Did you solve this issue, I face the same problem after I update the nvcc from 10.2 to 11.2

**Comment by hurun** [comment] 2022-09-14 08:07
anyone fixed this error, the same proble happen

**Comment by SawyDust1228** [comment] 2022-09-14 08:14
> 
when you use cmake, you can add -DCMAKE_CUDA_COMPILER=$(which nvcc) command.

**Comment by arithy** [comment] 2023-09-23 04:57
This issue can be caused by too long a value in the environment variable `PATH`.
In my case, it was resolved by removing unnecessary entries from `PATH`.
