### ISSUE TITLE
ERROR    Failed to load training data: Cannot load NeRF data from an empty set of paths.

### ISSUE THREAD

**Issue by coronet1127** [NVlabs/instant-ngp#1177] opened 2023-01-11 09:13 UTC
open [instant-ngp.exe] and drag and drop [data/nerf/fox]folder 

18:10:47 SUCCESS  Initialized CUDA. Active GPU is #0: NVIDIA GeForce RTX 3070 [86]
18:10:54 ERROR    Failed to load training data: Cannot load NeRF data from an empty set of paths.
18:10:54 INFO     Loading network config from: .\configs\nerf\base.json
18:10:54 INFO     GridEncoding:  Nmin=16 b=1.38191 F=2 T=2^19 L=16
18:10:54 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
18:10:54 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
18:10:54 INFO       total_encoding_params=12196240 total_network_params=10240

**Comment by Tom94** [comment] 2023-01-11 09:22
Duplicate of https://github.com/NVlabs/instant-ngp/issues/1172

**Closed by Tom94** 2023-01-11 09:22 UTC
