### ISSUE TITLE
error : More than 1 Code Generation option is specified, this is only allowed if NVCC Compilation Type i s 'compile' or 'fatbin'.

### ISSUE THREAD

**Issue by jankaminski1** [NVlabs/instant-ngp#236] opened 2022-02-22 15:48 UTC
Hi, I have the following issue when I try to execute :

**cmake --build build --config RelWithDebInfo -j 16**

Then this error appears:

 glfw_objects.vcxproj -> C:\***\instant-ngp\build\dependencies\glfw\src\glfw_objects.dir\RelWithDebInfo\glfw_o
  bjects.lib
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.6.t
argets(630,9): error : More than 1 Code Generation option is specified, this is only allowed if NVCC Compilation Type i
s 'compile' or 'fatbin'. [C:\***\instant-ngp\build\optix_program.vcxproj]

Does anyone else have this problem?

**Comment by AsdaA3da** [comment] 2022-02-22 17:25
Same problem, no idea what to do with this.

**Comment by jcobreros** [comment] 2022-02-22 18:58
Same problem since the commits of the past 2 days

**Comment by jcobreros** [comment] 2022-02-22 19:08
Wow that was a quick! The latest commit fixes this issue. Thanks!

**Comment by Tom94** [comment] 2022-02-22 19:12
Sorry for the regression, everyone. Should be fixed now!

A recent submodule change might require you to perform after pulling to get working compilation.
```sh
git submodule sync --recursive
git submodule update --init --recursive
```

**Closed by Tom94** 2022-02-22 19:12 UTC
